[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "4L87uF2uMaVzVgXbiyeNat197256kDBai3AvU6KcqhU9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/evergreen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
